/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as InspektorRouteImport } from './routes/inspektor'
import { Route as PrerequisitoRouteImport } from './routes/prerequisito'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const InspektorRoute = InspektorRouteImport.update({
  id: '/inspektor',
  path: '/inspektor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrerequisitoRoute = PrerequisitoRouteImport.update({
  id: '/prerequisito',
  path: '/prerequisito',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/clientes': typeof ClientesRoute
  '/inspektor': typeof InspektorRoute
  '/prerequisito': typeof PrerequisitoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/clientes': typeof ClientesRoute
  '/inspektor': typeof InspektorRoute
  '/prerequisito': typeof PrerequisitoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/clientes': typeof ClientesRoute
  '/inspektor': typeof InspektorRoute
  '/prerequisito': typeof PrerequisitoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checklist' | '/clientes' | '/inspektor' | '/prerequisito'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checklist' | '/clientes' | '/inspektor' | '/prerequisito'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/clientes'
    | '/inspektor'
    | '/prerequisito'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  ClientesRoute: typeof ClientesRoute
  InspektorRoute: typeof InspektorRoute
  PrerequisitoRoute: typeof PrerequisitoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspektor': {
      id: '/inspektor'
      path: '/inspektor'
      fullPath: '/inspektor'
      preLoaderRoute: typeof InspektorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prerequisito': {
      id: '/prerequisito'
      path: '/prerequisito'
      fullPath: '/prerequisito'
      preLoaderRoute: typeof PrerequisitoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  ClientesRoute: ClientesRoute,
  InspektorRoute: InspektorRoute,
  PrerequisitoRoute: PrerequisitoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
